FROM centos:6
MAINTAINER  Guna Sekhar "ngsekhar12@gmail.com"
# Install centos-release-scl to get python27 package
RUN yum install -y centos-release-scl
# Install python27
RUN yum install -y python27
# # Install epel-release to get mongodb-server package
RUN yum -y install epel-release
# Install mongodb-server
RUN yum install -y mongodb-server
# Install wget to download Tomcat7 and install unzip to unzip downloaded Tomcat7
# Install Java and configure it
RUN yum -y install unzip wget java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-1.b14.el7_2.x86_64 && \
    export PATH=$PATH:$JAVA_HOME/bin && \
    export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
#Download Tomcat7 Zip Folder from http://ftp.riken.jp and unzip Downloaded Tomcat7 Zip Directory
RUN wget http://ftp.riken.jp/net/apache/tomcat/tomcat-7/v7.0.79/bin/apache-tomcat-7.0.79.zip && \
    unzip apache-tomcat-7.0.79.zip
# Remove Tomcat7 Zip Directory and also change permisssions for entire Tomcat Directory
RUN rm -rf apache-tomcat-7.0.79.zip && \
    chmod -R 755 /apache-tomcat-7.0.79/
# Add entrypoint to start Tomcat automatically when container start.
ENTRYPOINT cd /apache-tomcat-7.0.79/bin/ && ./startup.sh && /bin/bash